version: '3.7'
#
services:
  mysql:
    container_name: database-local
    image: postgres:15.3
    ports:
      - 5432:5432
    # volumes:
    #   - ./pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: testdatabase
